import { describe, expect, it } from 'vitest';
import { generateHooks } from './hooks-generator.js';
import type { SchemaDefinition } from './index.js';

const createTestSchema = (): Map<string, SchemaDefinition> => {
  const schemaMap = new Map<string, SchemaDefinition>();
  schemaMap.set('myapp', {
    tables: {
      contacts: {
        columns: {
          id: { type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
          name: { type: 'string' },
          email: { type: 'string' },
          created_at: { type: 'datetime', default: 'NOW()' },
        },
      },
      user_profiles: {
        columns: {
          id: { type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
          user_id: { type: 'uuid' },
          bio: { type: 'text', nullable: true },
        },
      },
    },
  });
  return schemaMap;
};

describe('generateHooks', () => {
  it('generates auto-generated header', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema);

    expect(result).toContain('// Auto-generated by @launchpad/db-engine');
    expect(result).toContain('// Do not edit this file manually');
  });

  it('generates imports from @launchpad/db/react', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema);

    expect(result).toContain("import { useQuery, useQueryOne } from '@launchpad/db/react';");
    expect(result).toContain(
      "import { useInsert, useUpdate, useDelete } from '@launchpad/db/react';"
    );
    expect(result).toContain("import type { UseQueryOptions } from '@launchpad/db/react';");
    expect(result).toContain(
      "import type { UseMutationOptions, InsertVariables, UpdateVariables, DeleteVariables } from '@launchpad/db/react';"
    );
  });

  it('generates type imports from types file', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema, { typesImportPath: './types' });

    expect(result).toContain("import type { Myapp } from './types';");
  });

  it('generates list query hook (plural)', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema);

    expect(result).toContain('export function useContacts(');
    expect(result).toContain("table: 'contacts'");
    expect(result).toContain('return useQuery<Myapp.Contacts>');
  });

  it('generates single query hook (singular)', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema);

    expect(result).toContain('export function useContact(id: string');
    expect(result).toContain("table: 'contacts'");
    expect(result).toContain('where: { id: { eq: id } }');
    expect(result).toContain('return useQueryOne<Myapp.Contacts>');
  });

  it('generates create mutation hook', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema);

    expect(result).toContain('export function useCreateContact(');
    expect(result).toContain('const mutation = useInsert<Myapp.Contacts>');
    expect(result).toContain("table: 'contacts'");
  });

  it('generates update mutation hook', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema);

    expect(result).toContain('export function useUpdateContact(');
    expect(result).toContain('const mutation = useUpdate<Myapp.Contacts>');
  });

  it('generates delete mutation hook', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema);

    expect(result).toContain('export function useDeleteContact(');
    expect(result).toContain('const mutation = useDelete<Myapp.Contacts>');
  });

  it('handles snake_case table names correctly', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema);

    expect(result).toContain('export function useUserProfiles(');
    expect(result).toContain('export function useUserProfile(id: string');
    expect(result).toContain('export function useCreateUserProfile(');
    expect(result).toContain('export function useUpdateUserProfile(');
    expect(result).toContain('export function useDeleteUserProfile(');
    expect(result).toContain("table: 'user_profiles'");
  });

  it('generates JSDoc comments for hooks', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema);

    expect(result).toContain('/** Query hook for fetching all contacts */');
    expect(result).toContain('/** Query hook for fetching a single contact by ID */');
    expect(result).toContain('/** Mutation hook for creating a contact */');
    expect(result).toContain('/** Mutation hook for updating a contact */');
    expect(result).toContain('/** Mutation hook for deleting a contact */');
  });

  it('generates section separator for each table', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema);

    expect(result).toContain('// ==================== Contacts ====================');
    expect(result).toContain('// ==================== UserProfiles ====================');
  });

  it('respects includeQueryHooks option', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema, { includeQueryHooks: false });

    expect(result).not.toContain('export function useContacts(');
    expect(result).not.toContain('export function useContact(');
    expect(result).toContain('export function useCreateContact(');
    expect(result).toContain('export function useUpdateContact(');
    expect(result).toContain('export function useDeleteContact(');
  });

  it('respects includeMutationHooks option', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema, { includeMutationHooks: false });

    expect(result).toContain('export function useContacts(');
    expect(result).toContain('export function useContact(');
    expect(result).not.toContain('export function useCreateContact(');
    expect(result).not.toContain('export function useUpdateContact(');
    expect(result).not.toContain('export function useDeleteContact(');
  });

  it('respects custom typesImportPath', () => {
    const schema = createTestSchema();
    const result = generateHooks(schema, { typesImportPath: './database-types' });

    expect(result).toContain("import type { Myapp } from './database-types';");
  });
});

describe('singularization', () => {
  it('singularizes -s ending correctly', () => {
    const schema = new Map<string, SchemaDefinition>();
    schema.set('test', {
      tables: {
        users: { columns: { id: { type: 'uuid' } } },
        posts: { columns: { id: { type: 'uuid' } } },
      },
    });

    const result = generateHooks(schema);

    expect(result).toContain('export function useUser(id: string');
    expect(result).toContain('export function usePost(id: string');
    expect(result).toContain('export function useCreateUser(');
    expect(result).toContain('export function useCreatePost(');
  });

  it('singularizes -ies ending correctly', () => {
    const schema = new Map<string, SchemaDefinition>();
    schema.set('test', {
      tables: {
        categories: { columns: { id: { type: 'uuid' } } },
        companies: { columns: { id: { type: 'uuid' } } },
      },
    });

    const result = generateHooks(schema);

    expect(result).toContain('export function useCategory(id: string');
    expect(result).toContain('export function useCompany(id: string');
    expect(result).toContain('export function useCreateCategory(');
    expect(result).toContain('export function useCreateCompany(');
  });

  it('singularizes -es ending correctly', () => {
    const schema = new Map<string, SchemaDefinition>();
    schema.set('test', {
      tables: {
        boxes: { columns: { id: { type: 'uuid' } } },
        watches: { columns: { id: { type: 'uuid' } } },
        dishes: { columns: { id: { type: 'uuid' } } },
      },
    });

    const result = generateHooks(schema);

    expect(result).toContain('export function useBox(id: string');
    expect(result).toContain('export function useWatch(id: string');
    expect(result).toContain('export function useDish(id: string');
  });

  it("handles words that don't end in s", () => {
    const schema = new Map<string, SchemaDefinition>();
    schema.set('test', {
      tables: {
        person: { columns: { id: { type: 'uuid' } } },
        staff: { columns: { id: { type: 'uuid' } } },
      },
    });

    const result = generateHooks(schema);

    expect(result).toContain('export function usePerson(id: string');
    expect(result).toContain('export function useStaff(id: string');
  });
});

describe('multiple schemas', () => {
  it('handles multiple schemas correctly', () => {
    const schemaMap = new Map<string, SchemaDefinition>();
    schemaMap.set('app_one', {
      tables: { items: { columns: { id: { type: 'uuid' } } } },
    });
    schemaMap.set('app_two', {
      tables: { things: { columns: { id: { type: 'uuid' } } } },
    });

    const result = generateHooks(schemaMap);

    expect(result).toContain("import type { AppOne, AppTwo } from './types';");
    expect(result).toContain('export function useItems(');
    expect(result).toContain('export function useThings(');
    expect(result).toContain('useQuery<AppOne.Items>');
    expect(result).toContain('useQuery<AppTwo.Things>');
  });
});

describe('empty schema', () => {
  it('handles empty schema gracefully', () => {
    const schemaMap = new Map<string, SchemaDefinition>();

    const result = generateHooks(schemaMap);

    expect(result).toContain('// Auto-generated by @launchpad/db-engine');
    expect(result).not.toContain('export function use');
  });
});
