import { describe, expect, it } from 'vitest';
import { generateHooks } from './hooks-generator.js';
import type { SchemaDefinition } from './index.js';

describe('generateHooks', () => {
  const sampleSchema: SchemaDefinition = {
    tables: {
      users: {
        columns: {
          id: { type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
          email: { type: 'string', unique: true },
          name: { type: 'string', nullable: true },
          created_at: { type: 'datetime', default: 'NOW()' },
          updated_at: { type: 'datetime', default: 'NOW()' },
        },
      },
      posts: {
        columns: {
          id: { type: 'uuid', primaryKey: true, default: 'gen_random_uuid()' },
          title: { type: 'string' },
          content: { type: 'text' },
          author_id: { type: 'uuid', references: { table: 'users', column: 'id' } },
          created_at: { type: 'datetime', default: 'NOW()' },
        },
      },
    },
  };

  const schemaWithIntPk: SchemaDefinition = {
    tables: {
      products: {
        columns: {
          product_id: { type: 'integer', primaryKey: true },
          name: { type: 'string' },
          price: { type: 'decimal' },
        },
      },
    },
  };

  const schemaWithCategories: SchemaDefinition = {
    tables: {
      categories: {
        columns: {
          id: { type: 'uuid', primaryKey: true },
          name: { type: 'string' },
        },
      },
    },
  };

  it('generates auto-generated header', () => {
    const schemas = new Map([['app', sampleSchema]]);
    const result = generateHooks(schemas);

    expect(result).toContain('// Auto-generated by @launchpad/db-engine');
    expect(result).toContain('// Do not edit this file manually');
  });

  it('generates imports from @launchpad/db', () => {
    const schemas = new Map([['app', sampleSchema]]);
    const result = generateHooks(schemas);

    expect(result).toContain(
      "import { useQuery, useQuerySingle, useInsert, useUpdate, useDelete } from '@launchpad/db';"
    );
    expect(result).toContain("import type { QueryOptions, MutationOptions } from '@launchpad/db';");
  });

  it('generates type imports from types file', () => {
    const schemas = new Map([['app', sampleSchema]]);
    const result = generateHooks(schemas);

    expect(result).toContain("from './types';");
    expect(result).toContain('App.Users');
    expect(result).toContain('App.Posts');
  });

  it('generates list query hook (plural)', () => {
    const schemas = new Map([['app', sampleSchema]]);
    const result = generateHooks(schemas);

    expect(result).toContain('export function useUsers(');
    expect(result).toContain("options?: Omit<QueryOptions<App.Users>, 'table'>");
    expect(result).toContain("return useQuery<App.Users>({ ...options, table: 'users' });");

    expect(result).toContain('export function usePosts(');
    expect(result).toContain("options?: Omit<QueryOptions<App.Posts>, 'table'>");
    expect(result).toContain("return useQuery<App.Posts>({ ...options, table: 'posts' });");
  });

  it('generates single record query hook (singular)', () => {
    const schemas = new Map([['app', sampleSchema]]);
    const result = generateHooks(schemas);

    expect(result).toContain('export function useUser(');
    expect(result).toContain('id: string,');
    expect(result).toContain('return useQuerySingle<App.Users>({');
    expect(result).toContain("table: 'users',");
    expect(result).toContain("filter: { column: 'id', operator: 'eq', value: id },");

    expect(result).toContain('export function usePost(');
  });

  it('generates insert mutation hook', () => {
    const schemas = new Map([['app', sampleSchema]]);
    const result = generateHooks(schemas);

    expect(result).toContain('export function useInsertUser(');
    expect(result).toContain(
      "options?: Omit<MutationOptions<App.Users, { data: App.UsersInsert }>, 'table'>"
    );
    expect(result).toContain("return useInsert<App.Users>({ ...options, table: 'users' });");

    expect(result).toContain('export function useInsertPost(');
  });

  it('generates update mutation hook', () => {
    const schemas = new Map([['app', sampleSchema]]);
    const result = generateHooks(schemas);

    expect(result).toContain('export function useUpdateUser(');
    expect(result).toContain(
      "options?: Omit<MutationOptions<App.Users, { id: string; data: App.UsersUpdate }>, 'table'>"
    );
    expect(result).toContain("return useUpdate<App.Users>({ ...options, table: 'users' });");
  });

  it('generates delete mutation hook', () => {
    const schemas = new Map([['app', sampleSchema]]);
    const result = generateHooks(schemas);

    expect(result).toContain('export function useDeleteUser(');
    expect(result).toContain("options?: Omit<MutationOptions<App.Users, { id: string }>, 'table'>");
    expect(result).toContain("return useDelete<App.Users>({ ...options, table: 'users' });");
  });

  it('detects custom primary key column', () => {
    const schemas = new Map([['inventory', schemaWithIntPk]]);
    const result = generateHooks(schemas);

    expect(result).toContain('export function useProduct(');
    expect(result).toContain('product_id: number,');
    expect(result).toContain(
      "filter: { column: 'product_id', operator: 'eq', value: product_id },"
    );
  });

  it('uses number type for integer/bigint primary keys', () => {
    const schemas = new Map([['inventory', schemaWithIntPk]]);
    const result = generateHooks(schemas);

    expect(result).toContain('product_id: number,');
    expect(result).toContain('{ product_id: number; data: Inventory.ProductsUpdate }');
    expect(result).toContain('{ product_id: number }');
  });

  it('handles singular/plural naming - categories to category', () => {
    const schemas = new Map([['store', schemaWithCategories]]);
    const result = generateHooks(schemas);

    expect(result).toContain('export function useCategories(');
    expect(result).toContain('export function useCategory(');
    expect(result).toContain('export function useInsertCategory(');
    expect(result).toContain('export function useUpdateCategory(');
    expect(result).toContain('export function useDeleteCategory(');
  });

  it('includes JSDoc comments by default', () => {
    const schemas = new Map([['app', sampleSchema]]);
    const result = generateHooks(schemas);

    expect(result).toContain('/**');
    expect(result).toContain(' * Fetch all users records with optional filtering');
    expect(result).toContain(' * @table users');
    expect(result).toContain(' */');

    expect(result).toContain(' * Fetch a single users record by id');
    expect(result).toContain(' * Insert a new users record');
    expect(result).toContain(' * Update an existing users record');
    expect(result).toContain(' * Delete a users record');
  });

  it('excludes JSDoc comments when includeJsDoc is false', () => {
    const schemas = new Map([['app', sampleSchema]]);
    const result = generateHooks(schemas, { includeJsDoc: false });

    expect(result).not.toContain('/**');
    expect(result).not.toContain('@table');
  });

  it('uses custom types import path', () => {
    const schemas = new Map([['app', sampleSchema]]);
    const result = generateHooks(schemas, { typesImportPath: '../generated/database-types' });

    expect(result).toContain("from '../generated/database-types';");
  });

  it('handles multiple schemas', () => {
    const schemas = new Map([
      ['public', sampleSchema],
      ['inventory', schemaWithIntPk],
    ]);
    const result = generateHooks(schemas);

    expect(result).toContain('Public.Users');
    expect(result).toContain('Public.Posts');
    expect(result).toContain('Inventory.Products');
  });

  it('generates 5 hooks per table', () => {
    const schemas = new Map([['app', sampleSchema]]);
    const result = generateHooks(schemas);

    const userHooks = [
      'useUsers(',
      'useUser(',
      'useInsertUser(',
      'useUpdateUser(',
      'useDeleteUser(',
    ];

    for (const hook of userHooks) {
      expect(result).toContain(hook);
    }

    const postHooks = [
      'usePosts(',
      'usePost(',
      'useInsertPost(',
      'useUpdatePost(',
      'useDeletePost(',
    ];

    for (const hook of postHooks) {
      expect(result).toContain(hook);
    }
  });

  it('handles tables without explicit primary key (defaults to id)', () => {
    const schemaWithoutPk: SchemaDefinition = {
      tables: {
        items: {
          columns: {
            id: { type: 'uuid' },
            name: { type: 'string' },
          },
        },
      },
    };
    const schemas = new Map([['app', schemaWithoutPk]]);
    const result = generateHooks(schemas);

    expect(result).toContain('id: string,');
    expect(result).toContain("filter: { column: 'id', operator: 'eq', value: id },");
  });

  it('handles tables with addresses (pluralization edge case)', () => {
    const schemaWithAddresses: SchemaDefinition = {
      tables: {
        addresses: {
          columns: {
            id: { type: 'uuid', primaryKey: true },
            street: { type: 'string' },
          },
        },
      },
    };
    const schemas = new Map([['app', schemaWithAddresses]]);
    const result = generateHooks(schemas);

    expect(result).toContain('export function useAddresses(');
    expect(result).toContain('export function useAddress(');
    expect(result).toContain('export function useInsertAddress(');
    expect(result).toContain('export function useUpdateAddress(');
    expect(result).toContain('export function useDeleteAddress(');
  });
});
